apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  {{- include "cluster-discovery.argocdSyncWaveAnnotations" (dict "root" . "wave" "namespace") | nindent 2 }}
  labels:
    {{- include "cluster-discovery.labels" . | nindent 4 }}
