#!/usr/bin/env bash
# Discover OpenShift cluster settings from the current oc login and write Helm values.
#
# Usage:
#   ./scripts/discover-cluster-values.sh
#   ./scripts/discover-cluster-values.sh --output gitops/helm/acs-ai-overwatch/values-cluster.yaml
#
# Optional environment variables:
#   QUAY_REGISTRY_PASSWORD   If set, written to values-cluster.yaml (not committed by default if you gitignore the file).
#   KAGENTI_API_BASE_URL     Override detected Kagenti API URL.
#   GIT_REPO_URL             Override detected Git remote URL.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="${REPO_ROOT}/gitops/helm/acs-ai-overwatch/values-cluster.yaml"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output|-o)
      OUTPUT="$2"
      shift 2
      ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Required command not found: $1" >&2
    exit 1
  }
}

require_cmd oc

if ! oc whoami >/dev/null 2>&1; then
  echo "Not logged into a cluster. Run: oc login ..." >&2
  exit 1
fi

APPS_DOMAIN="$(oc get ingresses.config cluster -o jsonpath='{.spec.domain}')"
if [[ -z "${APPS_DOMAIN}" ]]; then
  echo "Could not read cluster ingress domain (ingresses.config/cluster)." >&2
  exit 1
fi

CLUSTER_NAME="$(oc get infrastructure cluster -o jsonpath='{.status.infrastructureName}' 2>/dev/null || true)"
if [[ -z "${CLUSTER_NAME}" ]]; then
  CLUSTER_NAME="$(oc config view --minify -o jsonpath='{.contexts[0].context.cluster}' 2>/dev/null || echo "openshift-cluster")"
fi

API_SERVER="$(oc whoami --show-server)"

# Quay route (if already deployed); otherwise use standard QuayRegistry route naming.
QUAY_HOST=""
if oc get namespace quay >/dev/null 2>&1; then
  QUAY_HOST="$(oc get route -n quay -o jsonpath='{range .items[*]}{.spec.host}{"\n"}{end}' 2>/dev/null | head -n1 || true)"
fi
if [[ -z "${QUAY_HOST}" ]]; then
  QUAY_HOST="quay-quay.apps.${APPS_DOMAIN}"
fi

# Kagenti API route (best-effort search).
KAGENTI_BASE="${KAGENTI_API_BASE_URL:-}"
if [[ -z "${KAGENTI_BASE}" ]]; then
  for ns in kagenti-system kagenti-system kagenti default; do
    host="$(oc get route -n "${ns}" -o jsonpath='{range .items[*]}{.spec.host}{"\n"}{end}' 2>/dev/null | grep -i kagenti | head -n1 || true)"
    if [[ -n "${host}" ]]; then
      KAGENTI_BASE="https://${host}"
      break
    fi
  done
fi
if [[ -z "${KAGENTI_BASE}" ]]; then
  KAGENTI_BASE="https://kagenti-api.apps.${APPS_DOMAIN}"
fi

# Git remote for Argo CD / Kagenti AppSource / Tekton.
GIT_URL="${GIT_REPO_URL:-}"
if [[ -z "${GIT_URL}" ]] && command -v git >/dev/null 2>&1; then
  raw="$(git -C "${REPO_ROOT}" config --get remote.origin.url 2>/dev/null || true)"
  case "${raw}" in
    git@*:*/*)
      GIT_URL="https://${raw#git@}"
      GIT_URL="${GIT_URL/:/\/}"
      GIT_URL="${GIT_URL%.git}.git"
      ;;
    *)
      GIT_URL="${raw}"
      ;;
  esac
fi
if [[ -z "${GIT_URL}" ]]; then
  GIT_URL="https://github.com/RedCupofJoe/acs-ai-overwatch.git"
fi

# Suggest NVMe device paths from the first schedulable worker (operator must still verify).
NVME_SUGGEST_METADATA=""
NVME_SUGGEST_OBJECT=""
WORKER="$(oc get nodes -l 'node-role.kubernetes.io/worker=' -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)"
if [[ -n "${WORKER}" ]]; then
  mapfile -t NVME_PATHS < <(oc debug "node/${WORKER}" --quiet -- chroot /host bash -c 'ls -1 /dev/disk/by-id/nvme-* 2>/dev/null | grep -v part | head -4' 2>/dev/null || true)
  if [[ ${#NVME_PATHS[@]} -ge 1 ]]; then
    NVME_SUGGEST_METADATA="${NVME_PATHS[0]}"
  fi
  if [[ ${#NVME_PATHS[@]} -ge 2 ]]; then
    NVME_SUGGEST_OBJECT="${NVME_PATHS[1]}"
  fi
fi

PASSWORD_LINE=""
if [[ -n "${QUAY_REGISTRY_PASSWORD:-}" ]]; then
  PASSWORD_LINE="    password: ${QUAY_REGISTRY_PASSWORD}"
fi

mkdir -p "$(dirname "${OUTPUT}")"

cat >"${OUTPUT}" <<EOF
# Generated by scripts/discover-cluster-values.sh — safe to commit (no secrets unless QUAY_REGISTRY_PASSWORD was set).
# Cluster API: ${API_SERVER}
# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

cluster:
  name: ${CLUSTER_NAME}
  appsDomain: ${APPS_DOMAIN}

mattermost:
  siteUrl: ""
  route:
    host: ""

quayStorage:
  registryCredentials:
    server: ${QUAY_HOST}
$(if [[ -n "${PASSWORD_LINE}" ]]; then echo "${PASSWORD_LINE}"; fi)

kagenti:
  api:
    baseUrl: ${KAGENTI_BASE}
  appSource:
    repoUrl: ${GIT_URL}
EOF

POC_FILE="${REPO_ROOT}/gitops/helm/acs-ai-overwatch/values-poc.yaml"
if [[ -n "${NVME_SUGGEST_METADATA}" && -n "${NVME_SUGGEST_OBJECT}" && -f "${POC_FILE}" ]]; then
  if grep -q 'REPLACE_METADATA_DISK' "${POC_FILE}"; then
    if [[ "$(uname)" == "Darwin" ]]; then
      sed -i '' "s|/dev/disk/by-id/nvme-REPLACE_METADATA_DISK|${NVME_SUGGEST_METADATA}|g" "${POC_FILE}"
      sed -i '' "s|/dev/disk/by-id/nvme-REPLACE_OBJECT_DISK|${NVME_SUGGEST_OBJECT}|g" "${POC_FILE}"
    else
      sed -i "s|/dev/disk/by-id/nvme-REPLACE_METADATA_DISK|${NVME_SUGGEST_METADATA}|g" "${POC_FILE}"
      sed -i "s|/dev/disk/by-id/nvme-REPLACE_OBJECT_DISK|${NVME_SUGGEST_OBJECT}|g" "${POC_FILE}"
    fi
  fi
fi

echo "Wrote ${OUTPUT}"
echo "  cluster.appsDomain: ${APPS_DOMAIN}"
echo "  cluster.name:         ${CLUSTER_NAME}"
echo "  quay server:          ${QUAY_HOST}"
echo "  kagenti.api.baseUrl:  ${KAGENTI_BASE}"
echo "  kagenti.appSource.repoUrl: ${GIT_URL}"
if [[ -n "${NVME_SUGGEST_METADATA}" ]]; then
  echo "  suggested metadata disk: ${NVME_SUGGEST_METADATA}"
  echo "  suggested object disk:   ${NVME_SUGGEST_OBJECT}"
  echo "  (updated values-poc.yaml devicePaths when placeholders were present)"
fi
echo ""
echo "Next: helm template / Argo CD sync with valueFiles including values-cluster.yaml"
