#!/usr/bin/env bash
# Discover OpenShift cluster settings from the current oc login and write Helm values.
#
# Usage:
#   ./scripts/discover-cluster-values.sh
#   ./scripts/discover-cluster-values.sh --output gitops/helm/acs-ai-overwatch/values-cluster.yaml
#   ./scripts/discover-cluster-values.sh --apply-configmap
#
# For full pre-GitOps setup (RBAC, namespaces, ConfigMap, discovery SA), use:
#   ./scripts/cluster-admin/install-pre-gitops.sh
#
# Optional environment variables:
#   QUAY_REGISTRY_PASSWORD   If set, written to values-cluster.yaml (not committed by default if you gitignore the file).
#   KAGENTI_API_BASE_URL     Override detected Kagenti API URL.
#   GIT_REPO_URL             Override detected Git remote URL.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=lib/openshift-cluster-discovery.sh
source "${REPO_ROOT}/scripts/lib/openshift-cluster-discovery.sh"

OUTPUT="${REPO_ROOT}/gitops/helm/acs-ai-overwatch/values-cluster.yaml"

APPLY_CONFIGMAP=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output|-o)
      OUTPUT="$2"
      shift 2
      ;;
    --apply-configmap)
      APPLY_CONFIGMAP=true
      shift
      ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Required command not found: $1" >&2
    exit 1
  }
}

require_cmd oc

if ! oc whoami >/dev/null 2>&1; then
  echo "Not logged into a cluster. Run: oc login ..." >&2
  exit 1
fi

export REPO_ROOT
openshift_discover_run

API_SERVER="$(oc whoami --show-server)"

PASSWORD_LINE=""
if [[ -n "${QUAY_REGISTRY_PASSWORD:-}" ]]; then
  PASSWORD_LINE="    password: ${QUAY_REGISTRY_PASSWORD}"
fi

mkdir -p "$(dirname "${OUTPUT}")"

{
  echo "# Generated by scripts/discover-cluster-values.sh — safe to commit (no secrets unless QUAY_REGISTRY_PASSWORD was set)."
  echo "# Cluster API: ${API_SERVER}"
  echo "# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo ""
  openshift_discover_write_helm_values \
    "${APPS_DOMAIN}" \
    "${CLUSTER_NAME}" \
    "${QUAY_REGISTRY_SERVER}" \
    "${KAGENTI_API_BASE_URL}" \
    "${GIT_REPO_URL}" \
    "${PASSWORD_LINE}"
} >"${OUTPUT}"

echo "Wrote ${OUTPUT}"
echo "  cluster.appsDomain: ${APPS_DOMAIN}"
echo "  cluster.name:         ${CLUSTER_NAME}"
echo "  quay server:          ${QUAY_REGISTRY_SERVER}"
echo "  kagenti.api.baseUrl:  ${KAGENTI_API_BASE_URL}"
echo "  kagenti.appSource.repoUrl: ${GIT_REPO_URL}"
if [[ "${APPLY_CONFIGMAP}" == true ]]; then
  chmod +x "${REPO_ROOT}/scripts/cluster-admin/03-apply-cluster-configmap.sh"
  exec "${REPO_ROOT}/scripts/cluster-admin/03-apply-cluster-configmap.sh"
fi

echo ""
echo "GitOps: run ./scripts/cluster-admin/install-pre-gitops.sh or sync Application acs-ai-overwatch-cluster-discovery."
