#!/usr/bin/env bash
# Discover OpenShift cluster settings from the current oc login and write Helm values.
#
# Usage:
#   ./scripts/discover-cluster-values.sh
#   ./scripts/discover-cluster-values.sh --output gitops/helm/acs-ai-overwatch/values-cluster.yaml
#
# Optional environment variables:
#   QUAY_REGISTRY_PASSWORD   If set, written to values-cluster.yaml (not committed by default if you gitignore the file).
#   KAGENTI_API_BASE_URL     Override detected Kagenti API URL.
#   GIT_REPO_URL             Override detected Git remote URL.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=lib/openshift-cluster-discovery.sh
source "${REPO_ROOT}/scripts/lib/openshift-cluster-discovery.sh"

OUTPUT="${REPO_ROOT}/gitops/helm/acs-ai-overwatch/values-cluster.yaml"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output|-o)
      OUTPUT="$2"
      shift 2
      ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Required command not found: $1" >&2
    exit 1
  }
}

require_cmd oc

if ! oc whoami >/dev/null 2>&1; then
  echo "Not logged into a cluster. Run: oc login ..." >&2
  exit 1
fi

export REPO_ROOT
openshift_discover_run

API_SERVER="$(oc whoami --show-server)"

PASSWORD_LINE=""
if [[ -n "${QUAY_REGISTRY_PASSWORD:-}" ]]; then
  PASSWORD_LINE="    password: ${QUAY_REGISTRY_PASSWORD}"
fi

mkdir -p "$(dirname "${OUTPUT}")"

{
  echo "# Generated by scripts/discover-cluster-values.sh — safe to commit (no secrets unless QUAY_REGISTRY_PASSWORD was set)."
  echo "# Cluster API: ${API_SERVER}"
  echo "# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo ""
  openshift_discover_write_helm_values \
    "${APPS_DOMAIN}" \
    "${CLUSTER_NAME}" \
    "${QUAY_REGISTRY_SERVER}" \
    "${KAGENTI_API_BASE_URL}" \
    "${GIT_REPO_URL}" \
    "${PASSWORD_LINE}"
} >"${OUTPUT}"

POC_FILE="${REPO_ROOT}/gitops/helm/acs-ai-overwatch/values-poc.yaml"
NVME_SUGGEST_METADATA=""
NVME_SUGGEST_OBJECT=""
WORKER="$(oc get nodes -l 'node-role.kubernetes.io/worker=' -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)"
if [[ -n "${WORKER}" ]]; then
  NVME_LIST="$(oc debug "node/${WORKER}" --quiet -- chroot /host bash -c 'ls -1 /dev/disk/by-id/nvme-* 2>/dev/null | grep -v part | head -4' 2>/dev/null || true)"
  NVME_SUGGEST_METADATA="$(printf '%s\n' "${NVME_LIST}" | sed -n '1p')"
  NVME_SUGGEST_OBJECT="$(printf '%s\n' "${NVME_LIST}" | sed -n '2p')"
fi

if [[ -n "${NVME_SUGGEST_METADATA}" && -n "${NVME_SUGGEST_OBJECT}" && -f "${POC_FILE}" ]]; then
  if grep -q 'REPLACE_METADATA_DISK' "${POC_FILE}"; then
    if [[ "$(uname)" == "Darwin" ]]; then
      sed -i '' "s|/dev/disk/by-id/nvme-REPLACE_METADATA_DISK|${NVME_SUGGEST_METADATA}|g" "${POC_FILE}"
      sed -i '' "s|/dev/disk/by-id/nvme-REPLACE_OBJECT_DISK|${NVME_SUGGEST_OBJECT}|g" "${POC_FILE}"
    else
      sed -i "s|/dev/disk/by-id/nvme-REPLACE_METADATA_DISK|${NVME_SUGGEST_METADATA}|g" "${POC_FILE}"
      sed -i "s|/dev/disk/by-id/nvme-REPLACE_OBJECT_DISK|${NVME_SUGGEST_OBJECT}|g" "${POC_FILE}"
    fi
  fi
fi

echo "Wrote ${OUTPUT}"
echo "  cluster.appsDomain: ${APPS_DOMAIN}"
echo "  cluster.name:         ${CLUSTER_NAME}"
echo "  quay server:          ${QUAY_REGISTRY_SERVER}"
echo "  kagenti.api.baseUrl:  ${KAGENTI_API_BASE_URL}"
echo "  kagenti.appSource.repoUrl: ${GIT_REPO_URL}"
if [[ -n "${NVME_SUGGEST_METADATA}" ]]; then
  echo "  suggested metadata disk: ${NVME_SUGGEST_METADATA}"
  echo "  suggested object disk:   ${NVME_SUGGEST_OBJECT}"
  echo "  (updated values-poc.yaml devicePaths when placeholders were present)"
fi
echo ""
echo "GitOps: sync Application acs-ai-overwatch-cluster-discovery (writes ConfigMap), then refresh acs-ai-overwatch."
