{{- if and .Values.accelerators.enabled .Values.accelerators.nfd.enabled }}
{{- if include "acs-ai-overwatch.createNamespaces" . }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.accelerators.nfd.namespace }}
  {{- include "acs-ai-overwatch.argocdSyncWaveAnnotations" (dict "root" . "wave" "namespace") | nindent 2 }}
  labels:
    openshift.io/cluster-monitoring: {{ .Values.accelerators.nfd.clusterMonitoringLabel | quote }}
---
{{- end }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.accelerators.nfd.operatorGroup.name }}
  {{- include "acs-ai-overwatch.argocdSyncWaveAnnotations" (dict "root" . "wave" "operators") | nindent 2 }}
  namespace: {{ .Values.accelerators.nfd.namespace }}
spec:
  targetNamespaces:
    - {{ .Values.accelerators.nfd.namespace }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.accelerators.nfd.subscription.name }}
  {{- include "acs-ai-overwatch.argocdSyncWaveAnnotations" (dict "root" . "wave" "operators") | nindent 2 }}
  namespace: {{ .Values.accelerators.nfd.namespace }}
spec:
  channel: {{ include "acs-ai-overwatch.operatorChannel" (dict "root" . "key" "nfdOperatorChannel" "default" .Values.accelerators.nfd.subscription.channel) }}
  installPlanApproval: {{ .Values.accelerators.nfd.subscription.installPlanApproval }}
  name: {{ .Values.accelerators.nfd.subscription.name }}
  source: {{ .Values.accelerators.nfd.subscription.source }}
  sourceNamespace: {{ .Values.accelerators.nfd.subscription.sourceNamespace }}
{{- end }}
