{{- if and .Values.accelerators.enabled .Values.accelerators.gpuOperator.enabled }}
apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: {{ .Values.accelerators.clusterPolicy.name }}
  {{- include "acs-ai-overwatch.argocdSyncWaveAnnotations" (dict "root" . "wave" "platformCRs") | nindent 2 }}
  labels:
    {{- include "acs-ai-overwatch.labels" . | nindent 4 }}
spec:
  operator:
    defaultRuntime: crio
  driver:
    enabled: true
  toolkit:
    enabled: true
  devicePlugin:
    enabled: true
    config:
      name: {{ .Values.accelerators.timeSlicing.configMapName }}
      default: {{ .Values.accelerators.timeSlicing.configKey }}
  dcgm:
    enabled: true
  gfd:
    enabled: true
  migManager:
    enabled: false
{{- end }}
