{{- if and .Values.accelerators.enabled .Values.accelerators.gpuOperator.enabled }}
apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: {{ .Values.accelerators.clusterPolicy.name }}
  {{- include "acs-ai-overwatch.argocdPlatformCrAnnotations" (dict "root" . "wave" "platformCRs") | nindent 2 }}
  labels:
    {{- include "acs-ai-overwatch.labels" . | nindent 4 }}
spec:
  operator:
    defaultRuntime: {{ .Values.accelerators.clusterPolicy.operator.defaultRuntime }}
    use_ocp_driver_toolkit: {{ .Values.accelerators.clusterPolicy.operator.use_ocp_driver_toolkit }}
  daemonsets:
    {{- toYaml .Values.accelerators.clusterPolicy.daemonsets | nindent 4 }}
  driver:
    {{- toYaml .Values.accelerators.clusterPolicy.driver | nindent 4 }}
  toolkit:
    {{- toYaml .Values.accelerators.clusterPolicy.toolkit | nindent 4 }}
  devicePlugin:
    enabled: {{ .Values.accelerators.clusterPolicy.devicePlugin.enabled }}
    config:
      name: {{ .Values.accelerators.timeSlicing.configMapName }}
      default: {{ .Values.accelerators.timeSlicing.configKey }}
  dcgm:
    {{- toYaml .Values.accelerators.clusterPolicy.dcgm | nindent 4 }}
  dcgmExporter:
    {{- toYaml .Values.accelerators.clusterPolicy.dcgmExporter | nindent 4 }}
  gfd:
    {{- toYaml .Values.accelerators.clusterPolicy.gfd | nindent 4 }}
  nodeStatusExporter:
    {{- toYaml .Values.accelerators.clusterPolicy.nodeStatusExporter | nindent 4 }}
  migManager:
    {{- toYaml .Values.accelerators.clusterPolicy.migManager | nindent 4 }}
{{- end }}
