{{- if .Values.components.acsPolicies.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.acs.testRange.namespace }}
  {{- include "acs-ai-overwatch.argocdSyncWaveAnnotations" (dict "root" . "wave" "namespace") | nindent 2 }}
  labels:
    {{- include "acs-ai-overwatch.labels" . | nindent 4 }}
{{- end }}
