{{- if .Values.components.acsPolicies.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.acs.testRange.namespace }}
  labels:
    {{- include "acs-ai-overwatch.labels" . | nindent 4 }}
{{- end }}
