{{- if and .Values.mattermost.enabled (include "acs-ai-overwatch.createNamespaces" .) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.mattermost.namespace }}
  {{- include "acs-ai-overwatch.argocdSyncWaveAnnotations" (dict "root" . "wave" "mattermostPrep") | nindent 2 }}
  labels:
    openshift.io/cluster-monitoring: "true"
{{- end }}
