{{- if .Values.mattermost.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.mattermost.namespace }}
  {{- include "acs-ai-overwatch.argocdSyncWaveAnnotations" (dict "root" . "wave" "namespace") | nindent 2 }}
  labels:
    openshift.io/cluster-monitoring: "true"
{{- end }}
