{{- if and .Values.quayStorage.enabled .Values.quayStorage.quayRegistry.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.quayStorage.quayRegistry.namespace }}
  {{- include "acs-ai-overwatch.argocdSyncWaveAnnotations" (dict "root" . "wave" "namespace") | nindent 2 }}
  labels:
    openshift.io/cluster-monitoring: {{ .Values.quayStorage.quayRegistry.clusterMonitoringLabel | quote }}
{{- end }}
