{{- if and .Values.rhoai.enabled (include "acs-ai-overwatch.crdReady" (dict "root" . "crdName" .Values.platformResources.crds.dataScienceCluster)) }}
apiVersion: {{ .Values.rhoai.datascienceCluster.apiVersion }}
kind: DataScienceCluster
metadata:
  name: {{ .Values.rhoai.datascienceCluster.name }}
  {{- include "acs-ai-overwatch.argocdPlatformCrAnnotations" (dict "root" . "wave" "platformCRs") | nindent 2 }}
  labels:
    {{- include "acs-ai-overwatch.labels" . | nindent 4 }}
spec:
  components:
{{- toYaml .Values.rhoai.datascienceCluster.components | nindent 4 }}
{{- end }}
