{{- if .Values.rhoai.enabled }}
{{- if include "acs-ai-overwatch.createNamespaces" . }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.rhoai.operator.namespace }}
  {{- include "acs-ai-overwatch.argocdSyncWaveAnnotations" (dict "root" . "wave" "namespace") | nindent 2 }}
  labels:
    openshift.io/cluster-monitoring: {{ .Values.rhoai.operator.clusterMonitoringLabel | quote }}
---
{{- end }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.rhoai.operator.operatorGroup.name }}
  {{- include "acs-ai-overwatch.argocdSyncWaveAnnotations" (dict "root" . "wave" "operators") | nindent 2 }}
  namespace: {{ .Values.rhoai.operator.namespace }}
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.rhoai.operator.subscription.name }}
  {{- include "acs-ai-overwatch.argocdSyncWaveAnnotations" (dict "root" . "wave" "operators") | nindent 2 }}
  namespace: {{ .Values.rhoai.operator.namespace }}
spec:
  channel: {{ include "acs-ai-overwatch.operatorChannel" (dict "root" . "key" "rhoaiOperatorChannel" "default" .Values.rhoai.operator.subscription.channel) }}
  installPlanApproval: {{ .Values.rhoai.operator.subscription.installPlanApproval }}
  name: {{ .Values.rhoai.operator.subscription.name }}
  source: {{ .Values.rhoai.operator.subscription.source }}
  sourceNamespace: {{ .Values.rhoai.operator.subscription.sourceNamespace }}
{{- end }}
