{{- if .Values.rhoai.enabled }}
apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: {{ .Values.rhoai.datascienceCluster.name }}
  {{- include "acs-ai-overwatch.argocdSyncWaveAnnotations" (dict "root" . "wave" "platformCRs") | nindent 2 }}
  labels:
    {{- include "acs-ai-overwatch.labels" . | nindent 4 }}
spec:
  components:
{{- toYaml .Values.rhoai.datascienceCluster.components | nindent 4 }}
{{- end }}
